product-name: pivotal-mysql
network-properties:
  singleton_availability_zone:
    name: us-central1-a
  other_availability_zones:
  - name: us-central1-a
  - name: us-central1-b
  - name: us-central1-c
  network:
    name: pas
  service_network:
    name: services
product-properties:
  .properties.plan1_selector.single_node.az_multi_select:
    value:
    - us-central1-a
    - us-central1-b
    - us-central1-c
  .properties.plan2_selector:
    value: Inactive
  .properties.plan3_selector:
    value: Inactive
  .properties.global_recipient_email:
    value: fbloggs@gmail.com    
  .properties.backups_selector:
    value: GCS
  .properties.backups_selector.gcs.project_id:
    value: ((gcp-project-id))
  .properties.backups_selector.gcs.bucket_name:
    value: ((gcp-project-id))-mysql-backups
  .properties.backups_selector.gcs.service_account_json:
    value:
      secret: '"this_is": "dummy_json"'
  .properties.deprecated_bindings_string:
    value: X
errand-config:
  upgrade-all-service-instances:
    post-deploy-state: false
resource-config:
